# Generated by Django 4.2 on 2024-12-15 19:02
__all__ = ()

import django.db.migrations


class Migration(django.db.migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        django.db.migrations.CreateModel(
            name="CustomRating",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("star_ratings.rating",),
        ),
    ]
