# Generated by Django 4.2 on 2024-12-04 11:11

from django.db import migrations, models
import django.db.models.deletion
import users.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="страна"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="Введите дату рождения",
                null=True,
                validators=[users.validators.validate_birthday],
                verbose_name="день рождения",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Расскажите о себе",
                null=True,
                verbose_name="о себе",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.user_directory_path,
            ),
        ),
        migrations.CreateModel(
            name="ProfileLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("vk", "VK"),
                            ("gitlub", "GitLub"),
                            ("github", "GitHub"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="тип сайта",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Полная ссылка, например, https://example.com",
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="users.profile",
                        verbose_name="профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "ссылка",
                "verbose_name_plural": "ссылки",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="город"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.country",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.city",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.country",
            ),
        ),
    ]
