# Generated by Django 4.2 on 2024-12-04 14:30
__all__ = ()
import django.db.migrations
import django.db.models
import django.db.models.deletion
import smart_selects.db_fields

import users.models
import users.validators


class Migration(django.db.migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        django.db.migrations.AddField(
            model_name="profile",
            name="city",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="country",
                chained_model_field="country",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.city",
                verbose_name="Город",
            ),
        ),
        django.db.migrations.AddField(
            model_name="profile",
            name="country",
            field=django.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.country",
                verbose_name="Страна",
            ),
        ),
        django.db.migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=django.db.models.DateField(
                blank=True,
                help_text="Введите дату рождения",
                null=True,
                validators=[users.validators.validate_birthday],
                verbose_name="день рождения",
            ),
        ),
        django.db.migrations.AlterField(
            model_name="profile",
            name="description",
            field=django.db.models.TextField(
                blank=True,
                help_text="Расскажите о себе",
                null=True,
                verbose_name="о себе",
            ),
        ),
        django.db.migrations.AlterField(
            model_name="profile",
            name="image",
            field=django.db.models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.user_directory_path,
            ),
        ),
        django.db.migrations.CreateModel(
            name="ProfileLink",
            fields=[
                (
                    "id",
                    django.db.models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_type",
                    django.db.models.CharField(
                        blank=True,
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("vk", "VK"),
                            ("gitlub", "GitLub"),
                            ("github", "GitHub"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="тип сайта",
                    ),
                ),
                (
                    "url",
                    django.db.models.URLField(
                        blank=True,
                        help_text="Полная ссылка, например, "
                                  "https://example.com",
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "profile",
                    django.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="users.profile",
                        verbose_name="профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "ссылка",
                "verbose_name_plural": "ссылки",
            },
        ),
    ]
