# Generated by Django 4.2 on 2024-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customrating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomRating",
        ),
        migrations.AlterField(
            model_name="profilelink",
            name="site_type",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("instagram", "Instagram"),
                    ("vk", "VK"),
                    ("gitlab", "GitLab"),
                    ("github", "GitHub"),
                ],
                max_length=20,
                verbose_name="тип сайта",
            ),
        ),
    ]
