# Generated by Django 4.2 on 2024-12-04 18:07
__all__ = ()

import django.db.migrations
import django.db.models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(django.db.migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        (
            "users",
            "0002_profile_city_profile_country_"
            "alter_profile_birthday_and_more",
        ),
    ]

    operations = [
        django.db.migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    django.db.models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.country",
                        verbose_name="Country",
                    ),
                ),
            ],
        ),
        django.db.migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    django.db.models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        blank=True,
                        chained_field="country",
                        chained_model_field="country",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.city",
                    ),
                ),
                (
                    "country",
                    django.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.country",
                        verbose_name="Country",
                    ),
                ),
            ],
        ),
        django.db.migrations.AlterField(
            model_name="profile",
            name="city",
            field=django.db.models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.city",
            ),
        ),
        django.db.migrations.AlterField(
            model_name="profile",
            name="country",
            field=django.db.models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.country",
            ),
        ),
    ]
