# Generated by Django 4.2 on 2024-12-03 15:21
__all__ = ()

import django.db.migrations
import django.db.models


class Migration(django.db.migrations.Migration):

    dependencies = [
        ("users", "0002_country_alter_profile_birthday_and_more"),
    ]

    operations = [
        django.db.migrations.AlterField(
            model_name="profilelink",
            name="site_type",
            field=django.db.models.CharField(
                blank=True,
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("instagram", "Instagram"),
                    ("vk", "VK"),
                    ("gitlub", "GitLub"),
                    ("github", "GitHub"),
                ],
                max_length=20,
                null=True,
                verbose_name="тип сайта",
            ),
        ),
        django.db.migrations.AlterField(
            model_name="profilelink",
            name="url",
            field=django.db.models.URLField(
                blank=True,
                help_text="Полная ссылка, например, https://example.com",
                null=True,
                verbose_name="URL",
            ),
        ),
    ]
