# Generated by Django 4.2 on 2024-12-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_alter_vacancy_required_experience"),
        ("vacancies", "0004_vacancy_need_count_users_alter_vacancy_status"),
    ]

    operations = []
