# Generated by Django 4.2 on 2024-12-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "vacancies",
            "0004_vacancy_hackaton_title_alter_vacancy_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentvacancy",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "комментарий к вакансии",
                "verbose_name_plural": "комментарии к вакансиям",
            },
        ),
        migrations.AlterModelOptions(
            name="ip",
            options={
                "verbose_name": "IP адрес",
                "verbose_name_plural": "IP адреса",
            },
        ),
    ]
