# Generated by Django 4.2 on 2024-12-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_alter_vacancy_required_experience"),
        ("vacancies", "0005_alter_vacancy_required_experience_and_more"),
    ]

    operations = []
