# Generated by Django 4.2 on 2024-12-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0005_alter_commentvacancy_options_alter_ip_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="deadline",
            field=models.DateField(
                blank=True,
                help_text="Крайний срок подачи заявок",
                null=True,
                verbose_name="дедлайн",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="required_experience",
            field=models.IntegerField(
                blank=True,
                help_text="Укажите количество лет опыта, необходимого для кандидата",
                null=True,
                verbose_name="требуемый опыт (в годах)",
            ),
        ),
    ]
