# Generated by Django 4.2 on 2024-12-19 13:26

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0006_merge_20241219_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=tinymce.models.HTMLField(
                help_text="Описание вакансии должно быть от 5 до 10000 символов",
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Описание не может быть таким коротким"
                    ),
                    django.core.validators.MaxLengthValidator(
                        10000, "Описание не может быть таким длинным"
                    ),
                ],
                verbose_name="описание вакансии",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="required_experience",
            field=models.CharField(
                choices=[
                    ("no_expirience", "Нет опыта"),
                    ("up_to_6_months", "До 6 месяцев"),
                    ("6_to_12_months", "От 6 до 12 месяцев"),
                    ("more_than_12_months", "Более 1 года"),
                ],
                default="no_expirience",
                help_text="Укажите количество опыта необходимого для кандидата",
                max_length=300,
                verbose_name="требуемый опыт",
            ),
        ),
    ]
